# Elysion - Projekt Setup Generator (erweitert mit API Gateway + BFF)
$mdFile = "PROJECT_SETUP.md"

# Datei neu erstellen / leeren
"" | Out-File $mdFile -Encoding UTF8

function Add-Line($text) {
    Write-Host $text
    Add-Content -Path $mdFile -Value $text
}

Add-Line "# Elysion – Projekt Setup"
Add-Line ""
Add-Line "## Ziel"
Add-Line "Eine Open-Source Alternative zu Mural mit Angular, React/tldraw, NestJS, Yjs und .NET."
Add-Line ""
Add-Line "## Architekturüberblick (Kurz)"
Add-Line "- Frontend: Angular + React/tldraw"
Add-Line "- Realtime: NestJS (WebSocket + Yjs)"
Add-Line "- BFF: UI-spezifische Aggregation (NestJS empfohlen)"
Add-Line "- API Gateway: zentrale Eintrittsstelle (TLS, Auth, Rate limiting, Routing)"
Add-Line "- Business Backend: .NET 8 Web API"
Add-Line "- Storage: PostgreSQL, Redis, MinIO"
Add-Line "- Infrastruktur: Docker + Traefik (Gateway) + CI/CD"
Add-Line ""
Add-Line "## Detaillierte Architektur"
Add-Line ""
Add-Line "### 1. Edge / API Gateway"
Add-Line "- Aufgaben: TLS Termination, Auth Validation (JWT/OIDC), CORS, Rate Limiting, Routing, Observability"
Add-Line "- Routenbeispiele:"
Add-Line "  - /api/* -> BFF"
Add-Line "  - /realtime/* -> Realtime (WebSocket Gateway)"
Add-Line "  - /internal/* -> Business Backend (nur intern, mTLS optional)"
Add-Line ""
Add-Line "### 2. Backend for Frontend (BFF)"
Add-Line "- Dünner Service, speziell für das Web-Frontend"
Add-Line "- UI-optimierte Aggregation von Business-APIs"
Add-Line "- Caching für UI-heavy Queries (Redis)"
Add-Line "- Token-Exchange / Short-lived tokens für WebSocket-Handshake"
Add-Line "- Implementierungsempfehlung: NestJS (wiederverwendbare Guards/Interceptors)"
Add-Line ""
Add-Line "### 3. Realtime Backend (NestJS)"
Add-Line "- WebSocket Gateway für CRDT-Synchronisation (Yjs)"
Add-Line "- Presence Service (Redis) für Cursor/Avatare"
Add-Line "- Session-Management und Auth-Validierung beim Handshake"
Add-Line "- Skalierung: horizontale Instanzen + Redis für Presence"
Add-Line ""
Add-Line "### 4. Business Backend (.NET 8)"
Add-Line "- Domain-Logik, Persistenz, Templates, Export-Service"
Add-Line "- Exponiert granulare REST/GRPC APIs für interne Nutzung"
Add-Line "- Keine direkte Internet-Exposition; nur über Gateway/BFF"
Add-Line ""
Add-Line "### 5. Storage & Persistenz"
Add-Line "- PostgreSQL: Users, Boards, Templates, Audit Logs"
Add-Line "- Redis: Presence, Session TTL, Cache"
Add-Line "- MinIO: Uploads, Exports, Template-Assets"
Add-Line ""
Add-Line "### 6. Authentifizierung & Security"
Add-Line "- Gateway validiert OIDC/JWT; BFF erhält User-Context"
Add-Line "- Interne Calls: service-to-service JWT oder mTLS"
Add-Line "- WebSocket: Token-Validierung beim Handshake; optional Short-lived WS-Tokens"
Add-Line ""
Add-Line "### 7. Observability & Operations"
Add-Line "- Zentralisiertes Logging (ELK/Datadog), Tracing (OpenTelemetry)"
Add-Line "- Metrics pro Route; Health Checks für Services"
Add-Line "- Rate Limiting am Gateway; Circuit Breaker intern"
Add-Line ""
Add-Line "### 8. Deployment & Infrastruktur"
Add-Line "- Traefik als Edge Gateway (oder spez. API Gateway wenn benötigt)"
Add-Line "- Container: BFF, Realtime, Business, DB, Redis, MinIO"
Add-Line "- Orchestrierung: Docker Compose für PoC, Kubernetes für Produktion"
Add-Line "- CI/CD: GitHub Actions / Azure DevOps Pipelines"
Add-Line ""
Add-Line "## Datenfluss (Beispiel)"
Add-Line "1. Web App lädt Board-Metadaten:"
Add-Line "   - Frontend -> Gateway -> BFF -> Business Backend -> PostgreSQL"
Add-Line "2. Echtzeit-Sync:"
Add-Line "   - Frontend (WS) -> Gateway -> Realtime Backend (Yjs) -> andere Clients"
Add-Line "3. Präsenz/Cursor:"
Add-Line "   - Realtime Backend -> Redis -> Broadcast an Clients"
Add-Line ""
Add-Line "## Vor- und Nachteile des Gateway + BFF Ansatzes"
Add-Line "- Vorteile:"
Add-Line "  - Zentrale Auth/Policy/Observability"
Add-Line "  - UI-optimierte Endpunkte via BFF (weniger Roundtrips)"
Add-Line "  - Klare Trennung von Verantwortlichkeiten"
Add-Line "- Nachteile:"
Add-Line "  - Zusätzliche Komponenten (BFF, Gateway) erhöhen Komplexität"
Add-Line "  - Mehr Deployments und Operational Overhead"
Add-Line ""
Add-Line "## Frontend Setup (Angular + React/tldraw)"
Add-Line "- Angular Projekt erstellen"
Add-Line "- React Canvas als Angular-Komponente einbetten"
Add-Line "- Yjs Client integrieren"
Add-Line "- WebSocket Client für Presence (via Gateway)"
Add-Line "- RxJS für State-Management"
Add-Line ""
Add-Line "## Realtime Backend Setup (NestJS)"
Add-Line "- NestJS Projekt erstellen"
Add-Line "- WebSocket Gateway implementieren"
Add-Line "- Yjs WebSocket Server integrieren"
Add-Line "- Redis Presence Layer implementieren"
Add-Line "- JWT-Validierung beim Handshake (Token vom Gateway/BFF)"
Add-Line ""
Add-Line "## BFF Setup (NestJS empfohlen)"
Add-Line "- Neues NestJS-Projekt als BFF"
Add-Line "- Endpoints für UI-Aggregationen erstellen"
Add-Line "- Caching (Redis) für heavy UI-Queries"
Add-Line "- Auth-Forwarding / Token-Exchange implementieren"
Add-Line ""
Add-Line "## Business Backend Setup (.NET 8)"
Add-Line "- ASP.NET Web API Projekt erstellen"
Add-Line "- Auth-Service (JWT/OIDC)"
Add-Line "- Board-Service (CRUD)"
Add-Line "- Template-Service"
Add-Line "- Export-Service (PNG/PDF)"
Add-Line ""
Add-Line "## Storage Setup"
Add-Line "- PostgreSQL für Boards, Templates, Users"
Add-Line "- Redis für Presence und Sessions"
Add-Line "- MinIO für Uploads und Exports"
Add-Line ""
Add-Line "## Infrastruktur Setup"
Add-Line "- Docker-Compose mit allen Services (PoC)"
Add-Line "- Traefik als Reverse Proxy / Gateway"
Add-Line "- Kubernetes Manifeste für Produktion"
Add-Line "- CI/CD mit GitHub Actions oder Azure DevOps"
Add-Line ""
Add-Line "## Nächste Schritte (konkret)"
Add-Line "- Gateway auswählen und Basis-Config (Traefik / Kong / APIM)"
Add-Line "- BFF-Skeleton (NestJS) erstellen"
Add-Line "- Realtime NestJS Gateway mit Yjs aufsetzen"
Add-Line "- .NET Web API scaffolden und DB-Migrationen anlegen"
Add-Line "- Infrastruktur: docker-compose.yml Vorlage erstellen"
Add-Line ""
Add-Line "## Projektname"
Add-Line "Gewählter Name: Elysion"
Add-Line ""
Add-Line "## Hinweise"
Add-Line "- Überlege Domain und GitHub-Repo: z. B. github.com/yourorg/elysion"
Add-Line "- Prüfe verfügbare Social Handles und Domain-Verfügbarkeit"
Add-Line "- Für PoC kann BFF + Realtime + Business in einer VM/Compose laufen; für Produktion trenne Services"
Add-Line ""
Add-Line "## Fertig!"
