// Runs `dotnet <args>` for this app and fails with a readable message when the .NET SDK is missing,
// so the root `pnpm build|test|lint` (pnpm -r) covers the business backend too.
import { spawnSync } from 'node:child_process';

const SOLUTION = 'Elysion.BusinessBackend.slnx';
const COMMANDS = {
  build: ['build', SOLUTION],
  test: ['test', SOLUTION],
  // Migrations are generated by `dotnet ef`; the formatter rewrites their encoding and style.
  lint: [
    'format',
    SOLUTION,
    '--verify-no-changes',
    '--exclude',
    'src/Elysion.BusinessBackend.Api/Data/Migrations',
  ],
};

const command = process.argv[2];
if (!COMMANDS[command]) {
  console.error(`Usage: node run-dotnet.mjs <${Object.keys(COMMANDS).join('|')}>`);
  process.exit(2);
}

const probe = spawnSync('dotnet', ['--version'], { encoding: 'utf8' });
if (probe.error || probe.status !== 0) {
  console.error(
    'The .NET SDK is required for apps/business-backend but `dotnet` was not found.\n' +
      'Install the .NET 10 SDK from https://dotnet.microsoft.com/download and retry.',
  );
  process.exit(1);
}

const result = spawnSync('dotnet', COMMANDS[command], { stdio: 'inherit', cwd: import.meta.dirname });
process.exit(result.status ?? 1);
