// Runs `dotnet build|test` and the JetBrains formatter (`format`, `lint`) for this app and fails with a readable message
// when the .NET SDK is missing. The root `pnpm build|test|lint|format` call it through `build:dotnet`, `test:dotnet`,
// `lint:dotnet` and `format:dotnet`.
//
// C# is formatted with the JetBrains command-line tools (`jb cleanupcode`, the local dotnet tool in dotnet-tools.json), not
// with `dotnet format`, using the style in `.editorconfig`. `cleanupcode` rewrites files and has no check mode, so `lint` runs it on a
// copy of the sources and reports the files that would change, leaving the working tree alone.
import { spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';

const here = import.meta.dirname;
const SOLUTION = 'Elysion.BusinessBackend.slnx';
const PROFILE = 'Built-in: Reformat Code';
// Migrations are generated by `dotnet ef`; the formatter would rewrite their style. Build output is not source.
const EXCLUDE = '**/Data/Migrations/**;**/bin/**;**/obj/**';

const dotnet = (args, cwd = here) => spawnSync('dotnet', args, { stdio: 'inherit', cwd });
const cleanup = (cwd) =>
  dotnet(
    [
      'jb',
      'cleanupcode',
      SOLUTION,
      `--profile=${PROFILE}`,
      `--exclude=${EXCLUDE}`,
      '--no-build',
      '--no-updates',
      '--verbosity=WARN',
    ],
    cwd,
  );

/** Every .cs file below `dir` that is formatted by the tool (not migrations, not build output), by relative path. */
function sources(dir) {
  const found = [];
  const walk = (current) => {
    for (const entry of readdirSync(current)) {
      if (['bin', 'obj', 'node_modules', '.vs'].includes(entry)) continue;
      const path = join(current, entry);
      if (statSync(path).isDirectory()) {
        if (relative(dir, path).split('\\').join('/') === 'src/Elysion.BusinessBackend.Api/Data/Migrations') continue;
        walk(path);
      } else if (entry.endsWith('.cs')) {
        found.push(relative(dir, path));
      }
    }
  };
  walk(dir);
  return found;
}

/** `lint`: format a copy, compare, and say which files differ. */
function lint() {
  const work = mkdtempSync(join(tmpdir(), 'elysion-format-'));
  try {
    // The copy sits in a folder of its own below a copy of the repository's root .editorconfig, so the style files that
    // apply are the same as for the real tree.
    const rootConfig = join(here, '..', '..', '.editorconfig');
    if (existsSync(rootConfig)) cpSync(rootConfig, join(work, '.editorconfig'));
    const copy = join(work, 'business-backend');
    cpSync(here, copy, {
      recursive: true,
      filter: (path) => !/[\\/](bin|obj|node_modules|\.vs)([\\/]|$)/.test(path),
    });
    if (dotnet(['restore', SOLUTION, '--verbosity', 'quiet'], copy).status !== 0) return 1;
    if (cleanup(copy).status !== 0) return 1;
    const changed = sources(here).filter(
      (file) => readFileSync(join(here, file), 'utf8') !== readFileSync(join(copy, file), 'utf8'),
    );
    if (changed.length > 0) {
      console.error(
        `These C# files are not formatted as the JetBrains tools would (${changed.length}):\n` +
          changed.map((file) => `  apps/business-backend/${file}`).join('\n') +
          '\nRun `pnpm format:dotnet` and commit the result.',
      );
      return 1;
    }
    return 0;
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

const COMMANDS = {
  build: () => dotnet(['build', SOLUTION]).status,
  test: () => dotnet(['test', SOLUTION]).status,
  format: () => {
    // `--no-build` needs what a build leaves behind (the restored packages and project data), so build first.
    const built = dotnet(['build', SOLUTION, '--verbosity', 'quiet']);
    return built.status === 0 ? cleanup(here).status : built.status;
  },
  lint,
};

const command = process.argv[2];
if (!COMMANDS[command]) {
  console.error(`Usage: node run-dotnet.mjs <${Object.keys(COMMANDS).join('|')}>`);
  process.exit(2);
}

const probe = spawnSync('dotnet', ['--version'], { encoding: 'utf8' });
if (probe.error || probe.status !== 0) {
  console.error(
    'The .NET SDK is required for apps/business-backend but `dotnet` was not found.\n' +
      'Install the .NET 10 SDK from https://dotnet.microsoft.com/download and retry.',
  );
  process.exit(1);
}

if (command === 'format' || command === 'lint') {
  // The JetBrains tools are a local dotnet tool: restore it (a no-op when it is there).
  const restored = dotnet(['tool', 'restore']);
  if (restored.status !== 0) {
    console.error('Could not restore the JetBrains command-line tools (dotnet tool restore).');
    process.exit(1);
  }
}

process.exit(COMMANDS[command]() ?? 1);
